### ISSUE TITLE
Perf: Consider casting SQL output using native SQL

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android-Backend#113]
One alternative that might be worth considering is casting the strftime output at the sql level. This would make the conversion more explicit, avoid the need for pasted-in code, and prevent accidental usage of a string when a number was expected.

```
sqlite> select cast("1.6" as int);
cast("1.6" as int) = 1
sqlite> select cast("1.6" as float);
cast("1.6" as float) = 1.6
```

_Originally posted by @dae in https://github.com/david-allison-1/Anki-Android-Backend/issues/111#issuecomment-853439435_

**Comment by mikehardy** [comment]
success criteria is that it meets the CursorWindow contract, that is the sqlite cast === strtoll ? (mostly I'm just active listening to make sure I understand these things)

**Comment by david-allison-1** [comment]
Yep. Additional acceptance criteria would be performance testing to ensure that this is faster.

I'm unsure about this one but it's worth investigating since we spend so much time in SQL: fixing the specific SQL statement is a definite yes. This will definitely be correct and will remove code, but we can't optimise this heavily with pre-knowledge of how the query will be cast as the 'execute stage': `query()` and 'retrieve stage': `getDouble()` logic are separate in the code.

It's also a rarely-used code path.

In my mind, the Java should be fairly fast, and the overhead from the JNI -> Rust -> SQLite might end up dominating the speed up from native code.

**Comment by dae** [comment]
Didn't realise Android's cursor explicitly supports this use case; that seems to remove most of the benefits changing the SQL would bring.
