### ISSUE TITLE
Add dependency bot

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android-Backend#167]
I don't think dependabot handles all the ecosystems necessary here (github actions, python, java, and rust)

If it does cool, if not there is another option https://docs.renovatebot.com/configuration-options/ (ACRA uses it, seems pretty good)

**Comment by mikehardy** [comment]
Integrated gradle update wrapper that's working well for Anki-Android in #170 / first example #171

**Comment by dae** [comment]
No Python anymore. The desktop JS has pinned versions which shouldn't change for a given release, so that doesn't need to be worried about, and presumably ignored by Dependabot as it's in a subrepo. Rust code gets automatically (but not completely) bumped when updating to a new desktop version, as that desktop version includes newer "x or later" versions for its dependencies. Dependabot handles Rust just fine, though I'd recommend using it only for security updates.

**Comment by mikehardy** [comment]
I think dependabot is doing a sufficient job here, not worth investing in a different setup at the moment
