### ISSUE TITLE
Is there artifact that I can use on PC ?

### ISSUE THREAD

**Issue by unoexperto** [ankidroid/Anki-Android-Backend#255]
Hi folks! Is there artifact that I can use on PC ? Basically I want to create anki deck programmatically. I'm using JVM language.

**Comment by mikehardy** [comment]
I'm not sure this is exactly what you're looking for but it *does* build an AAR that you could talk to using the JVM

You may also have an easier time using the "ContentProvider" (an Android concept) and building a Java-based android app that speaks to the "AnkiDroid API" on an installed AnkiDroid instance (which could be running in an Android emulator) and syncing that.

Those are both pretty advanced / fairly involved things to do though

You might have an easier time using whatever language you want to generate csv files and import those on AnkiDesktop - that's what I would do

**Comment by unoexperto** [comment]
@mikehardy In short my goal to generate anki deck file programmatically using JVM-based language. Currently I have to resort to a weird hack when I produce json on my Java code and them feed to small Python app that uses open-source library that can create anki files.

**Comment by mikehardy** [comment]
Okay, I believe I understood your requirement. I believe my comment is still accurate, except instead of generating CSV files and an import, you are doing JSON files and a Python app to import. That seems fine. The source is all open in all these components, so you could say from a certain perspective no hacks are "weird" - if the hack works, it works, and you're set. No one will take the software away or force you to upgrade (open source...) so that works.

This library is probably not the API you want, it's more of a build toolchain optimization to avoid normal AnkiDroid devs (Kotlin/Android programmers, at this point) from having to get a rust / node / python toolchain all working. In that sense it is very AnkiDroid specific, and while you could use it the way AnkiDroid does, I'm not sure it is worth the effort.

As mentioned, I'd just emit CSV and import if I were performing this task.
